version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: language-automation
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123!
      MYSQL_DATABASE: language
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d