spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:language}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password123!}
    driver-class-name: org.postgresql.Driver