spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:language}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password123!}
    driver-class-name: com.mysql.cj.jdbc.Driver